
import { stringify as stringifyYaml } from 'yaml';

import type { WorkflowInventory } from './inventory.js';

export function normalizeLockEol(text: string): string {
  return text.replace(/\r\n/g, '\n');
}

export const LOCK_FILENAME = 'entry.lock.yaml';

export const LOCK_VERSION = 1;

const HEADER =
  '# Generated by `riglane catalog pack`. Do not edit by hand —\n' +
  '# the catalog CI regenerates this inventory from the pinned commit\n' +
  '# and rejects the entry when it differs from what was submitted.\n';

export function composeLockDocument(inv: WorkflowInventory): string {
  const doc = {
    lock_version: LOCK_VERSION,
    workflow: inv.workflow,
    workflow_version: inv.workflow_version,
    workflow_sha256: inv.workflow_sha256,
    steps: inv.steps,
    params: inv.params,
    structs: inv.structs,
    script_tools: inv.script_tools,
    mcp_dependencies: inv.mcp_dependencies,
    deciders: inv.deciders,
    bundled_files: inv.bundled_files,
    capabilities: inv.capabilities,
  };
  return HEADER + stringifyYaml(doc, { lineWidth: 0 });
}
