
import { createHash } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmdirSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { join, resolve } from 'node:path';
import { parseArgs } from 'node:util';

import { PRODUCT_DIR } from '../config/paths.js';
import { AGENT_PREFIX, CLI_NAME, WORKFLOW_STEP_AGENT } from '../config/product.js';
import { ackGeminiAgents } from '../cli/gemini-agent-ack.js';
import { loadYaml } from '../engine/schema-validate.js';
import { collectAllSteps } from '../engine/workflow-tree.js';
import {
  DENY_SPELLINGS,
  SPEC_ENGINE_TOOLS,
  makeToolName,
  mcpServerToolName,
  normalizeName,
  profileNarrowedStep,
  resolveStepToolEntries,
  stepBranchProfiles,
  stepDeniedCapabilities,
  type BranchProfile,
} from '../engine/step-tool-rights.js';

export interface AgentProfile {
  readonly id: string;
  readonly def: BranchProfile;
}

function profileSuffix(profile?: AgentProfile): string {
  return profile !== undefined ? `--${profile.id}` : '';
}

function effectiveStep(
  step: Record<string, unknown>,
  profile?: AgentProfile,
): Record<string, unknown> {
  return profile !== undefined ? profileNarrowedStep(step, profile.def) : step;
}

function agentDescription(stepName: string, wfName: string, profile?: AgentProfile): string {
  const profileClause = profile !== undefined ? `, branch profile '${profile.id}'` : '';
  return `Workflow step subagent for '${stepName}' step of '${wfName}' workflow${profileClause}. Auto-generated — do not edit manually.`;
}

function agentOpeningLine(stepName: string, wfName: string, profile?: AgentProfile): string {
  const profileClause =
    profile !== undefined ? `, as its '${profile.id}' branch profile` : '';
  return `You are executing step '${stepName}' of workflow '${wfName}'${profileClause}.`;
}


export const AGENT_DIR = PRODUCT_DIR;
export const WORKFLOWS_DIR = join(AGENT_DIR, 'workflows');
export const TEMPLATES_DIR = join(WORKFLOWS_DIR, 'templates');
export function detectAgentFileHosts(cwd: string): {
  hasClaude: boolean;
  hasOpencode: boolean;
  hasCopilot: boolean;
  hasGemini: boolean;
  genClaude: boolean;
} {
  const hasClaude = existsSync(join(cwd, '.claude'));
  const hasOpencode = existsSync(join(cwd, '.opencode'));
  const hasCopilot = existsSync(join(cwd, '.github', 'hooks', 'riglane.json'));
  const hasGemini = existsSync(join(cwd, GEMINI_AGENTS_DIR, `${WORKFLOW_STEP_AGENT}.md`));
  return {
    hasClaude,
    hasOpencode,
    hasCopilot,
    hasGemini,
    genClaude: hasClaude || (!hasOpencode && !hasCopilot && !hasGemini),
  };
}

export function agentFileHostLabels(cwd: string): string[] {
  const h = detectAgentFileHosts(cwd);
  return [
    ...(h.genClaude ? ['Claude Code'] : []),
    ...(h.hasOpencode ? ['OpenCode'] : []),
    ...(h.hasCopilot ? ['Copilot'] : []),
    ...(h.hasGemini ? ['Gemini'] : []),
  ];
}

export const CLAUDE_AGENTS_DIR = join('.claude', 'agents');
export const OPENCODE_AGENTS_DIR = join('.opencode', 'agents');

export const COPILOT_AGENTS_DIR = join('.github', 'agents');

export const GEMINI_AGENTS_DIR = join('.gemini', 'agents');
export const WORKFLOW_TOOLS_PREFIX = 'mcp__workflow_tools__';
export const WORKFLOW_ENGINE_PREFIX = 'mcp__workflow_engine__';
export { SPEC_ENGINE_TOOLS, resolveStepToolEntries, stepAuthorsSpecs } from '../engine/step-tool-rights.js';
export type { StepToolEntry } from '../engine/step-tool-rights.js';
export const CLAUDE_SPAWN_DENIES: readonly string[] = ['Agent', 'Task'];
export function standardHooks(
  workflowName: string,
  stepName: string,
  root?: string,
  profileId?: string,
): string {
  const q = (s: string): string => JSON.stringify(s).slice(1, -1);
  const profileArg = profileId !== undefined ? ` --profile=${q(profileId)}` : '';
  const rootArg = root !== undefined && root !== '' ? ` --root=${q(root)}` : '';
  return `hooks:
  PreToolUse:
    - matcher: "Edit|Write"
      hooks:
        - type: command
          command: "${CLI_NAME} file-guard${rootArg}"
    - matcher: "mcp__.*"
      hooks:
        - type: command
          command: "${CLI_NAME} workflow-tool-validator --workflow=${q(workflowName)} --step=${q(stepName)}${profileArg}${rootArg}"
`;
}

export const GENERATED_MARKER = '# Auto-generated by init-workflow.py — DO NOT EDIT MANUALLY';


export class WorkflowNotFoundError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'WorkflowNotFoundError';
  }
}

export class WorkflowMalformedError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'WorkflowMalformedError';
  }
}

export class WorkflowFileWriteError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'WorkflowFileWriteError';
  }
}


export interface WorkflowDoc {
  name?: string;
  tools?: Array<Record<string, unknown>>;
  steps?: Array<Record<string, unknown>>;
  [key: string]: unknown;
}

export type WriteStatus = 'created' | 'updated' | 'unchanged';

export interface InitWorkflowResult {
  created: string[];
  updated: string[];
  unchanged: string[];
  deleted: string[];
  total: number;
}

export interface InitWorkflowOptions {
  readonly dryRun?: boolean;
  readonly cwd?: string;
  readonly stdout?: (s: string) => void;
  readonly stderr?: (s: string) => void;
  readonly modelOverride?: string;
}

interface ResolvedOptions {
  readonly dryRun: boolean;
  readonly cwd: string;
  readonly stdout: (s: string) => void;
  readonly stderr: (s: string) => void;
  readonly modelOverride?: string;
}

function resolveOpts(opts: InitWorkflowOptions = {}): ResolvedOptions {
  return {
    dryRun: opts.dryRun ?? false,
    cwd: opts.cwd ?? '.',
    stdout: opts.stdout ?? ((s: string) => void process.stdout.write(s)),
    stderr: opts.stderr ?? ((s: string) => void process.stderr.write(s)),
    ...(opts.modelOverride ? { modelOverride: opts.modelOverride } : {}),
  };
}


export function loadWorkflow(name: string, cwd = '.'): [string, WorkflowDoc] {
  const candidates = [
    join(cwd, TEMPLATES_DIR, 'my_workflows', name, 'workflow.yaml'),
    join(cwd, TEMPLATES_DIR, 'predefined', name, 'workflow.yaml'),
    join(cwd, TEMPLATES_DIR, 'examples', name, 'workflow.yaml'),
    join(cwd, TEMPLATES_DIR, 'community', name, 'workflow.yaml'),
    join(cwd, WORKFLOWS_DIR, name, 'workflow.yaml'),
  ];
  for (const path of candidates) {
    if (existsSync(path) && statSync(path).isFile()) {
      try {
        const data = loadYaml<WorkflowDoc>(path);
        return [path, data];
      } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        throw new WorkflowMalformedError(`failed to parse workflow.yaml: ${msg}`);
      }
    }
  }
  throw new WorkflowNotFoundError(
    `Workflow '${name}' not found. Searched:\n  ${candidates.join('\n  ')}`,
  );
}


export function subagentDir(workflowName: string, stepName: string): string {
  return `${workflowName}-${stepName}`;
}

export function opencodeAgentName(workflowName: string, stepName: string): string {
  return `${AGENT_PREFIX}${subagentDir(workflowName, stepName)}`;
}

export function scriptToolMcpName(workflowName: string, toolName: string): string {
  return `${WORKFLOW_TOOLS_PREFIX}${makeToolName(workflowName, toolName)}`;
}

export { mcpServerToolName };


export function deniedSpecTools(workflow: WorkflowDoc, step: Record<string, unknown>): string[] {
  const granted = new Set(
    resolveStepToolEntries(workflow, step)
      .filter((e) => e.kind === 'spec')
      .map((e) => e.tool),
  );
  return SPEC_ENGINE_TOOLS.filter((t) => !granted.has(t));
}

export function resolveStepTools(workflow: WorkflowDoc, step: Record<string, unknown>): string[] {
  const wfName = (workflow.name as string | undefined) ?? '';
  return resolveStepToolEntries(workflow, step).map((e) => {
    if (e.kind === 'script') return scriptToolMcpName(wfName, e.tool);
    if (e.kind === 'mcp') return mcpServerToolName(e.server ?? '', e.tool);
    return `${WORKFLOW_ENGINE_PREFIX}${e.tool}`;
  });
}

export function opencodeToolPermissions(
  workflow: WorkflowDoc,
  step: Record<string, unknown>,
): string[] {
  const wfName = (workflow.name as string | undefined) ?? '';
  return resolveStepToolEntries(workflow, step).map((e) => {
    if (e.kind === 'script') return `workflow_tools_${makeToolName(wfName, e.tool)}`;
    if (e.kind === 'mcp') return `${normalizeName(e.server ?? '')}_${normalizeName(e.tool)}`;
    return `workflow_engine_${e.tool}`;
  });
}

export function copilotStepTools(
  workflow: WorkflowDoc,
  step: Record<string, unknown>,
): string[] {
  const wfName = (workflow.name as string | undefined) ?? '';
  return resolveStepToolEntries(workflow, step).map((e) => {
    if (e.kind === 'script') return `workflow_tools-${makeToolName(wfName, e.tool)}`;
    if (e.kind === 'mcp') return `${normalizeName(e.server ?? '')}-${normalizeName(e.tool)}`;
    return `workflow_engine-${e.tool}`;
  });
}

export function geminiStepTools(
  workflow: WorkflowDoc,
  step: Record<string, unknown>,
): string[] {
  const wfName = (workflow.name as string | undefined) ?? '';
  return resolveStepToolEntries(workflow, step).map((e) => {
    if (e.kind === 'script') return `mcp_workflow_tools_${makeToolName(wfName, e.tool)}`;
    if (e.kind === 'mcp') return `mcp_${normalizeName(e.server ?? '')}_${normalizeName(e.tool)}`;
    return `mcp_workflow_engine_${e.tool}`;
  });
}



export function subagentSteps(workflow: WorkflowDoc): Array<[string, Record<string, unknown>]> {
  const out: Array<[string, Record<string, unknown>]> = [];
  for (const step of collectAllSteps({ steps: workflow.steps })) {
    if (step.subagent !== false) {
      const name = (step.name as string | undefined) ?? '';
      out.push([name, step]);
    }
  }
  return out;
}


export function agentModelForMode(mode: unknown): string {
  switch (mode) {
    case 'lightest':
      return 'haiku';
    case 'strongest':
      return 'opus';
    case 'inherit':
    case 'auto':
    default:
      return 'inherit';
  }
}

export function buildAgentMd(
  workflow: WorkflowDoc,
  step: Record<string, unknown>,
  modelOverride?: string,
  root?: string,
  profile?: AgentProfile,
): string {
  const wfName = (workflow.name as string | undefined) ?? '';
  const stepName = (step.name as string | undefined) ?? '';
  const subName = `${subagentDir(wfName, stepName)}${profileSuffix(profile)}`;

  const denied = [
    ...CLAUDE_SPAWN_DENIES,
    ...stepDeniedCapabilities(step).flatMap((c) => DENY_SPELLINGS[c].claude),
    ...deniedSpecTools(workflow, step).map((t) => `${WORKFLOW_ENGINE_PREFIX}${t}`),
  ];
  const modelValue = agentModelForMode(modelOverride ?? step.model);

  const description = agentDescription(stepName, wfName, profile);

  const body = `${agentOpeningLine(stepName, wfName, profile)}

## Your responsibilities

1. **Follow the goal** provided in the user message precisely
2. **Write outputs** to the paths specified in the goal
3. **Read inputs** listed in the goal for context
4. **Use the script/MCP tools** declared for this step — they are in your tool inventory
5. **Do not modify** engine infrastructure files — a PreToolUse hook enforces this
6. **Work alone** — never spawn subagents of your own: this step is executed by exactly one agent (you), and the gate follows only you

## Output quality

- **Follow struct schemas exactly.** Output must match the schema specified in the goal.
- Write to the **exact file path** specified.
- Use the declared tools for their intended purpose; do not invent shortcuts.

## What happens after you finish

A structural gate validates your outputs. If validation fails, you receive feedback
and should fix the issues. If it passes, the orchestrator proceeds to the next step.
`;

  const deniedLine = denied.length > 0 ? `disallowedTools: ${denied.join(', ')}\n` : '';

  const frontmatter = `---\nname: ${subName}\ndescription: ${description}\nmodel: ${modelValue}\n${deniedLine}maxTurns: 100\n${standardHooks(wfName, stepName, root, profile?.id)}---\n`;

  return `${frontmatter}\n${GENERATED_MARKER}\n\n${body}`;
}

export const OPENCODE_BUILTIN_ALLOWS: readonly string[] = [
  'read',
  'write',
  'edit',
  'apply_patch',
  'bash',
  'glob',
  'grep',
  'list',
  'todowrite',
  'webfetch',
  'websearch',
  'lsp',
  'skill',
];

export function buildOpencodeAgentMd(
  workflow: WorkflowDoc,
  step: Record<string, unknown>,
  profile?: AgentProfile,
): string {
  const wfName = (workflow.name as string | undefined) ?? '';
  const stepName = (step.name as string | undefined) ?? '';

  const description = agentDescription(stepName, wfName, profile);

  const denySet = new Set(
    stepDeniedCapabilities(step).flatMap((c) => DENY_SPELLINGS[c].opencode),
  );
  const permissionLines = [
    'permission:',
    '  "*": deny',
    ...OPENCODE_BUILTIN_ALLOWS.filter((t) => !denySet.has(t)).map((t) => `  ${t}: allow`),
    ...opencodeToolPermissions(workflow, effectiveStep(step, profile)).map(
      (t) => `  "${t}": allow`,
    ),
  ].join('\n');

  const body = `${agentOpeningLine(stepName, wfName, profile)}

## Your responsibilities

1. **Follow the goal** provided in the user message precisely
2. **Write outputs** to the paths specified in the goal
3. **Read inputs** listed in the goal for context
4. **Use the script/MCP tools** declared for this step — they are in your tool inventory
5. **Do not modify** engine infrastructure files (\`.riglane/scripts/\`, \`.riglane/tools/\`, \`.opencode/\`) — the Riglane hook plugin blocks \`edit\`/\`write\`/\`apply_patch\` there; do not work around it via \`bash\`
6. **Work alone** — never spawn subagents of your own: this step is executed by exactly one agent (you), and the gate follows only you

## Output quality

- **Follow struct schemas exactly.** Output must match the schema specified in the goal.
- Write to the **exact file path** specified.
- Use the declared tools for their intended purpose; do not invent shortcuts.

## What happens after you finish

A structural gate validates your outputs. If validation fails, the orchestrator
either resumes this session with the gate feedback (fix the reported issues and
finish) or starts a fresh attempt — the engine decides. If it passes, the
orchestrator proceeds to the next step.
`;

  const frontmatter = `---\ndescription: ${description}\nmode: subagent\nhidden: true\n${permissionLines}\n---\n`;

  return `${frontmatter}\n<!-- ${GENERATED_MARKER} -->\n\n${body}`;
}

export function writeOpencodeSubagent(
  workflow: WorkflowDoc,
  step: Record<string, unknown>,
  opts: InitWorkflowOptions = {},
  profile?: AgentProfile,
): [WriteStatus, string] {
  const r = resolveOpts(opts);
  const wfName = (workflow.name as string | undefined) ?? '';
  const stepName = (step.name as string | undefined) ?? '';
  const agentName = `${opencodeAgentName(wfName, stepName)}${profileSuffix(profile)}`;
  const agentsDir = join(r.cwd, OPENCODE_AGENTS_DIR);
  const agentPath = join(agentsDir, `${agentName}.md`);

  const newContent = buildOpencodeAgentMd(workflow, step, profile);

  let existingContent: string | null = null;
  if (existsSync(agentPath) && statSync(agentPath).isFile()) {
    try {
      existingContent = readFileSync(agentPath, 'utf-8');
    } catch {
      existingContent = null;
    }
  }

  if (existingContent === newContent) {
    return ['unchanged', agentName];
  }

  const status: WriteStatus = existingContent !== null ? 'updated' : 'created';

  if (!r.dryRun) {
    try {
      mkdirSync(agentsDir, { recursive: true });
      writeFileSync(agentPath, newContent, 'utf-8');
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      throw new WorkflowFileWriteError(`failed to write opencode subagent for ${stepName}: ${msg}`);
    }
  }

  return [status, agentName];
}

export function findOrphanOpencodeSubagents(
  workflowName: string,
  expectedNames: readonly string[],
  opts: InitWorkflowOptions = {},
): string[] {
  const r = resolveOpts(opts);
  const agentsDir = join(r.cwd, OPENCODE_AGENTS_DIR);
  if (!existsSync(agentsDir) || !statSync(agentsDir).isDirectory()) return [];

  const prefix = `${AGENT_PREFIX}${workflowName}-`;
  const expected = new Set(expectedNames);
  const found: string[] = [];

  const entries = readdirSync(agentsDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
    const agentName = entry.name.slice(0, -'.md'.length);
    if (!agentName.startsWith(prefix)) continue;
    if (expected.has(agentName)) continue;

    let content: string;
    try {
      content = readFileSync(join(agentsDir, entry.name), 'utf-8');
    } catch {
      continue;
    }
    if (content.includes(GENERATED_MARKER)) {
      found.push(agentName);
    }
  }
  return found.sort();
}

export function deleteOpencodeOrphan(name: string, opts: InitWorkflowOptions = {}): void {
  const r = resolveOpts(opts);
  const agentPath = join(r.cwd, OPENCODE_AGENTS_DIR, `${name}.md`);
  if (r.dryRun) return;
  try {
    if (existsSync(agentPath) && statSync(agentPath).isFile()) {
      unlinkSync(agentPath);
    }
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    r.stderr(`Failed to delete ${agentPath}: ${msg}\n`);
  }
}

export function copilotAgentName(workflowName: string, stepName: string): string {
  return `${AGENT_PREFIX}${subagentDir(workflowName, stepName)}`;
}

export function buildCopilotAgentMd(
  workflow: WorkflowDoc,
  step: Record<string, unknown>,
  profile?: AgentProfile,
): string {
  const wfName = (workflow.name as string | undefined) ?? '';
  const stepName = (step.name as string | undefined) ?? '';
  const agentName = `${copilotAgentName(wfName, stepName)}${profileSuffix(profile)}`;

  const description = agentDescription(stepName, wfName, profile);

  const copilotDenySet = new Set(
    stepDeniedCapabilities(step).flatMap((c) => DENY_SPELLINGS[c].copilot),
  );
  const allTools = ['read', 'edit', 'execute', 'search', 'web', 'todo']
    .filter((t) => !copilotDenySet.has(t))
    .concat(copilotStepTools(workflow, effectiveStep(step, profile)));
  const toolsLine = `tools: [${allTools.map((t) => JSON.stringify(t)).join(', ')}]`;

  const body = `${agentOpeningLine(stepName, wfName, profile)}

## Your responsibilities

1. **Follow the goal** provided in the user message precisely
2. **Write outputs** to the paths specified in the goal
3. **Read inputs** listed in the goal for context
4. **Use the script/MCP tools** declared for this step — they are in your tool inventory
5. **Do not modify** engine infrastructure files — a preToolUse hook enforces this
6. **Work alone** — never spawn subagents of your own: this step is executed by exactly one agent (you), and the gate follows only you

## Output quality

- **Follow struct schemas exactly.** Output must match the schema specified in the goal.
- Write to the **exact file path** specified.
- Use the declared tools for their intended purpose; do not invent shortcuts.

## What happens after you finish

A structural gate validates your outputs. If validation fails, the gate blocks
your stop and the feedback arrives as your next turn — fix the issues and finish
again. If it passes, the orchestrator proceeds to the next step.
`;

  const frontmatter = `---\nname: ${agentName}\ndescription: ${description}\n${toolsLine}\nuser-invocable: false\ndisable-model-invocation: true\n---\n`;

  return `${frontmatter}\n<!-- ${GENERATED_MARKER} -->\n\n${body}`;
}

export function writeCopilotSubagent(
  workflow: WorkflowDoc,
  step: Record<string, unknown>,
  opts: InitWorkflowOptions = {},
  profile?: AgentProfile,
): [WriteStatus, string] {
  const r = resolveOpts(opts);
  const wfName = (workflow.name as string | undefined) ?? '';
  const stepName = (step.name as string | undefined) ?? '';
  const agentName = `${copilotAgentName(wfName, stepName)}${profileSuffix(profile)}`;
  const agentsDir = join(r.cwd, COPILOT_AGENTS_DIR);
  const agentPath = join(agentsDir, `${agentName}.agent.md`);

  const newContent = buildCopilotAgentMd(workflow, step, profile);

  let existingContent: string | null = null;
  if (existsSync(agentPath) && statSync(agentPath).isFile()) {
    try {
      existingContent = readFileSync(agentPath, 'utf-8');
    } catch {
      existingContent = null;
    }
  }

  if (existingContent === newContent) {
    return ['unchanged', agentName];
  }

  const status: WriteStatus = existingContent !== null ? 'updated' : 'created';

  if (!r.dryRun) {
    try {
      mkdirSync(agentsDir, { recursive: true });
      writeFileSync(agentPath, newContent, 'utf-8');
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      throw new WorkflowFileWriteError(`failed to write copilot subagent for ${stepName}: ${msg}`);
    }
  }

  return [status, agentName];
}

export function findOrphanCopilotSubagents(
  workflowName: string,
  expectedNames: readonly string[],
  opts: InitWorkflowOptions = {},
): string[] {
  const r = resolveOpts(opts);
  const agentsDir = join(r.cwd, COPILOT_AGENTS_DIR);
  if (!existsSync(agentsDir) || !statSync(agentsDir).isDirectory()) return [];

  const prefix = `${AGENT_PREFIX}${workflowName}-`;
  const expected = new Set(expectedNames);
  const found: string[] = [];

  const entries = readdirSync(agentsDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.agent.md')) continue;
    const agentName = entry.name.slice(0, -'.agent.md'.length);
    if (!agentName.startsWith(prefix)) continue;
    if (expected.has(agentName)) continue;

    let content: string;
    try {
      content = readFileSync(join(agentsDir, entry.name), 'utf-8');
    } catch {
      continue;
    }
    if (content.includes(GENERATED_MARKER)) {
      found.push(agentName);
    }
  }
  return found.sort();
}

export function deleteCopilotOrphan(name: string, opts: InitWorkflowOptions = {}): void {
  const r = resolveOpts(opts);
  const agentPath = join(r.cwd, COPILOT_AGENTS_DIR, `${name}.agent.md`);
  if (r.dryRun) return;
  try {
    if (existsSync(agentPath) && statSync(agentPath).isFile()) {
      unlinkSync(agentPath);
    }
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    r.stderr(`Failed to delete ${agentPath}: ${msg}\n`);
  }
}

export function geminiAgentName(workflowName: string, stepName: string): string {
  return `${AGENT_PREFIX}${subagentDir(workflowName, stepName)}`;
}

export function buildGeminiAgentMd(
  workflow: WorkflowDoc,
  step: Record<string, unknown>,
  profile?: AgentProfile,
): string {
  const wfName = (workflow.name as string | undefined) ?? '';
  const stepName = (step.name as string | undefined) ?? '';
  const agentName = `${geminiAgentName(wfName, stepName)}${profileSuffix(profile)}`;

  const description = agentDescription(stepName, wfName, profile);

  const geminiDenySet = new Set(
    stepDeniedCapabilities(step).flatMap((c) => DENY_SPELLINGS[c].gemini),
  );
  const allTools = [
    'read_file',
    'read_many_files',
    'list_directory',
    'glob',
    'grep_search',
    'search_file_content',
    'write_file',
    'replace',
    'run_shell_command',
    'google_web_search',
    'web_fetch',
    'write_todos',
    'activate_skill',
    'get_internal_docs',
    'complete_task',
  ]
    .filter((t) => !geminiDenySet.has(t))
    .concat(geminiStepTools(workflow, effectiveStep(step, profile)));
  const toolsLine = `tools: [${allTools.map((t) => JSON.stringify(t)).join(', ')}]`;

  const body = `${agentOpeningLine(stepName, wfName, profile)}

## Your responsibilities

1. **Follow the goal** provided in the invocation prompt precisely
2. **Write outputs** to the paths specified in the goal
3. **Read inputs** listed in the goal for context
4. **Use the script/MCP tools** declared for this step — they are in your tool inventory
5. **Do not modify** engine infrastructure files — a BeforeTool hook enforces this
6. **Work alone** — never spawn subagents of your own: this step is executed by exactly one agent (you), and the gate follows only you

## Output quality

- **Follow struct schemas exactly.** Output must match the schema specified in the goal.
- Write to the **exact file path** specified.
- Use the declared tools for their intended purpose; do not invent shortcuts.

## Finishing

When your work is done, call **complete_task** with a short summary of what
you produced. A structural gate then validates your outputs. If validation
fails, the orchestrator re-spawns this agent with the failure feedback in the
prompt — address that feedback first, then redo the work and finish again.
`;

  const frontmatter = `---\nname: ${agentName}\ndescription: ${description}\n${toolsLine}\n---\n`;

  return `${frontmatter}\n<!-- ${GENERATED_MARKER} -->\n\n${body}`;
}

export function writeGeminiSubagent(
  workflow: WorkflowDoc,
  step: Record<string, unknown>,
  opts: InitWorkflowOptions = {},
  profile?: AgentProfile,
): [WriteStatus, string] {
  const r = resolveOpts(opts);
  const wfName = (workflow.name as string | undefined) ?? '';
  const stepName = (step.name as string | undefined) ?? '';
  const agentName = `${geminiAgentName(wfName, stepName)}${profileSuffix(profile)}`;
  const agentsDir = join(r.cwd, GEMINI_AGENTS_DIR);
  const agentPath = join(agentsDir, `${agentName}.md`);

  const newContent = buildGeminiAgentMd(workflow, step, profile);

  let existingContent: string | null = null;
  if (existsSync(agentPath) && statSync(agentPath).isFile()) {
    try {
      existingContent = readFileSync(agentPath, 'utf-8');
    } catch {
      existingContent = null;
    }
  }

  if (existingContent === newContent) {
    return ['unchanged', agentName];
  }

  const status: WriteStatus = existingContent !== null ? 'updated' : 'created';

  if (!r.dryRun) {
    try {
      mkdirSync(agentsDir, { recursive: true });
      writeFileSync(agentPath, newContent, 'utf-8');
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      throw new WorkflowFileWriteError(`failed to write gemini subagent for ${stepName}: ${msg}`);
    }
  }

  return [status, agentName];
}

export function findOrphanGeminiSubagents(
  workflowName: string,
  expectedNames: readonly string[],
  opts: InitWorkflowOptions = {},
): string[] {
  const r = resolveOpts(opts);
  const agentsDir = join(r.cwd, GEMINI_AGENTS_DIR);
  if (!existsSync(agentsDir) || !statSync(agentsDir).isDirectory()) return [];

  const prefix = `${AGENT_PREFIX}${workflowName}-`;
  const expected = new Set(expectedNames);
  const found: string[] = [];

  const entries = readdirSync(agentsDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
    const agentName = entry.name.slice(0, -'.md'.length);
    if (!agentName.startsWith(prefix)) continue;
    if (expected.has(agentName)) continue;

    let content: string;
    try {
      content = readFileSync(join(agentsDir, entry.name), 'utf-8');
    } catch {
      continue;
    }
    if (content.includes(GENERATED_MARKER)) {
      found.push(agentName);
    }
  }
  return found.sort();
}

export function deleteGeminiOrphan(name: string, opts: InitWorkflowOptions = {}): void {
  const r = resolveOpts(opts);
  const agentPath = join(r.cwd, GEMINI_AGENTS_DIR, `${name}.md`);
  if (r.dryRun) return;
  try {
    if (existsSync(agentPath) && statSync(agentPath).isFile()) {
      unlinkSync(agentPath);
    }
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    r.stderr(`Failed to delete ${agentPath}: ${msg}\n`);
  }
}


export function contentHash(text: string): string {
  return createHash('sha256').update(text, 'utf-8').digest('hex');
}

export function writeSubagent(
  workflow: WorkflowDoc,
  step: Record<string, unknown>,
  opts: InitWorkflowOptions = {},
  profile?: AgentProfile,
): [WriteStatus, string] {
  const r = resolveOpts(opts);
  const wfName = (workflow.name as string | undefined) ?? '';
  const stepName = (step.name as string | undefined) ?? '';
  const subDirName = `${subagentDir(wfName, stepName)}${profileSuffix(profile)}`;
  const subDir = join(r.cwd, CLAUDE_AGENTS_DIR, subDirName);
  const subPath = join(subDir, 'AGENT.md');

  const newContent = buildAgentMd(workflow, step, r.modelOverride, resolve(r.cwd), profile);

  let existingContent: string | null = null;
  if (existsSync(subPath) && statSync(subPath).isFile()) {
    try {
      existingContent = readFileSync(subPath, 'utf-8');
    } catch {
      existingContent = null;
    }
  }

  if (existingContent === newContent) {
    return ['unchanged', subDirName];
  }

  const status: WriteStatus = existingContent !== null ? 'updated' : 'created';

  if (!r.dryRun) {
    try {
      mkdirSync(subDir, { recursive: true });
      writeFileSync(subPath, newContent, 'utf-8');
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      throw new WorkflowFileWriteError(`failed to write subagent for ${stepName}: ${msg}`);
    }
  }

  return [status, subDirName];
}

export function findOrphanSubagents(
  workflowName: string,
  expectedDirNames: readonly string[],
  opts: InitWorkflowOptions = {},
): string[] {
  const r = resolveOpts(opts);
  const agentsDir = join(r.cwd, CLAUDE_AGENTS_DIR);
  if (!existsSync(agentsDir) || !statSync(agentsDir).isDirectory()) return [];

  const prefix = `${workflowName}-`;
  const expected = new Set(expectedDirNames);
  const found: string[] = [];

  const entries = readdirSync(agentsDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (!entry.name.startsWith(prefix)) continue;
    if (expected.has(entry.name)) continue;

    const fullPath = join(agentsDir, entry.name);
    const agentMd = join(fullPath, 'AGENT.md');
    if (!existsSync(agentMd) || !statSync(agentMd).isFile()) continue;

    let content: string;
    try {
      content = readFileSync(agentMd, 'utf-8');
    } catch {
      continue;
    }
    if (content.includes(GENERATED_MARKER)) {
      found.push(entry.name);
    }
  }
  return found.sort();
}

export function deleteOrphan(name: string, opts: InitWorkflowOptions = {}): void {
  const r = resolveOpts(opts);
  const fullPath = join(r.cwd, CLAUDE_AGENTS_DIR, name);
  const agentMd = join(fullPath, 'AGENT.md');
  if (r.dryRun) return;
  try {
    if (existsSync(agentMd) && statSync(agentMd).isFile()) {
      unlinkSync(agentMd);
    }
    rmdirSync(fullPath);
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    r.stderr(`Failed to delete ${fullPath}: ${msg}\n`);
  }
}


export function initWorkflowSync(
  name: string,
  opts: InitWorkflowOptions = {},
): InitWorkflowResult {
  const r = resolveOpts(opts);
  const [wfPath, workflow] = loadWorkflow(name, r.cwd);

  if (workflow === null || typeof workflow !== 'object' || Array.isArray(workflow)) {
    throw new WorkflowMalformedError(`workflow.yaml is not a mapping: ${wfPath}`);
  }

  const wfName = (workflow.name as string | undefined) || name;
  r.stdout(`Workflow: ${wfName} (${wfPath})\n`);

  const subSteps = subagentSteps(workflow);
  if (subSteps.length === 0) {
    r.stdout('  No subagent steps. Nothing to generate.\n');
    return { created: [], updated: [], unchanged: [], deleted: [], total: 0 };
  }

  const { hasOpencode, hasCopilot, hasGemini, genClaude } = detectAgentFileHosts(r.cwd);

  const created: string[] = [];
  const updated: string[] = [];
  const unchanged: string[] = [];
  const deleted: string[] = [];

  const record = (status: WriteStatus, name: string): void => {
    if (status === 'created') {
      created.push(name);
      r.stdout(`  CREATED  ${name}\n`);
    } else if (status === 'updated') {
      updated.push(name);
      r.stdout(`  UPDATED  ${name}\n`);
    } else {
      unchanged.push(name);
      r.stdout(`  UNCHANGED ${name}\n`);
    }
  };

  const agentProfiles = (step: Record<string, unknown>): AgentProfile[] =>
    Object.entries(stepBranchProfiles(step) ?? {}).map(([id, def]) => ({ id, def }));

  if (genClaude) {
    const expectedDirNames: string[] = [];
    for (const [stepName, step] of subSteps) {
      if (!stepName) {
        r.stderr('WARNING: step without name; skipping\n');
        continue;
      }
      const [status, dirName] = writeSubagent(workflow, step, opts);
      expectedDirNames.push(dirName);
      record(status, dirName);
      for (const profile of agentProfiles(step)) {
        const [pStatus, pDirName] = writeSubagent(workflow, step, opts, profile);
        expectedDirNames.push(pDirName);
        record(pStatus, pDirName);
      }
    }

    const orphans = findOrphanSubagents(wfName, expectedDirNames, opts);
    for (const orphan of orphans) {
      deleteOrphan(orphan, opts);
      deleted.push(orphan);
      r.stdout(`  DELETED  ${orphan} (orphan)\n`);
    }
  }

  if (hasOpencode) {
    const expectedAgentNames: string[] = [];
    for (const [stepName, step] of subSteps) {
      if (!stepName) {
        if (!genClaude) r.stderr('WARNING: step without name; skipping\n');
        continue;
      }
      const [status, agentName] = writeOpencodeSubagent(workflow, step, opts);
      expectedAgentNames.push(agentName);
      record(status, `${agentName}.md`);
      for (const profile of agentProfiles(step)) {
        const [pStatus, pName] = writeOpencodeSubagent(workflow, step, opts, profile);
        expectedAgentNames.push(pName);
        record(pStatus, `${pName}.md`);
      }
    }

    const ocOrphans = findOrphanOpencodeSubagents(wfName, expectedAgentNames, opts);
    for (const orphan of ocOrphans) {
      deleteOpencodeOrphan(orphan, opts);
      deleted.push(`${orphan}.md`);
      r.stdout(`  DELETED  ${orphan}.md (orphan)\n`);
    }
  }

  if (hasCopilot) {
    const expectedAgentNames: string[] = [];
    for (const [stepName, step] of subSteps) {
      if (!stepName) {
        if (!genClaude && !hasOpencode) r.stderr('WARNING: step without name; skipping\n');
        continue;
      }
      const [status, agentName] = writeCopilotSubagent(workflow, step, opts);
      expectedAgentNames.push(agentName);
      record(status, `${agentName}.agent.md`);
      for (const profile of agentProfiles(step)) {
        const [pStatus, pName] = writeCopilotSubagent(workflow, step, opts, profile);
        expectedAgentNames.push(pName);
        record(pStatus, `${pName}.agent.md`);
      }
    }

    const cpOrphans = findOrphanCopilotSubagents(wfName, expectedAgentNames, opts);
    for (const orphan of cpOrphans) {
      deleteCopilotOrphan(orphan, opts);
      deleted.push(`${orphan}.agent.md`);
      r.stdout(`  DELETED  ${orphan}.agent.md (orphan)\n`);
    }
  }

  if (hasGemini) {
    const expectedAgentNames: string[] = [];
    for (const [stepName, step] of subSteps) {
      if (!stepName) {
        if (!genClaude && !hasOpencode && !hasCopilot)
          r.stderr('WARNING: step without name; skipping\n');
        continue;
      }
      const [status, agentName] = writeGeminiSubagent(workflow, step, opts);
      expectedAgentNames.push(agentName);
      record(status, `${agentName}.md`);
      for (const profile of agentProfiles(step)) {
        const [pStatus, pName] = writeGeminiSubagent(workflow, step, opts, profile);
        expectedAgentNames.push(pName);
        record(pStatus, `${pName}.md`);
      }
    }

    const gmOrphans = findOrphanGeminiSubagents(wfName, expectedAgentNames, opts);
    for (const orphan of gmOrphans) {
      deleteGeminiOrphan(orphan, opts);
      deleted.push(`${orphan}.md`);
      r.stdout(`  DELETED  ${orphan}.md (orphan)\n`);
    }

    const acked = ackGeminiAgents(r.cwd, { dryRun: r.dryRun });
    if (acked.length > 0) {
      r.stdout(`  ACK      ${acked.length} gemini agent(s) acknowledged (headless consent)\n`);
    }
  }

  const total = created.length + updated.length + deleted.length;
  r.stdout('\n');
  r.stdout(
    `Summary: ${created.length} created, ${updated.length} updated, ` +
      `${unchanged.length} unchanged, ${deleted.length} deleted\n`,
  );

  if (total > 0) {
    const hosts = agentFileHostLabels(r.cwd);
    r.stdout('\n');
    r.stdout(`[!] Restart ${hosts.join(' / ')} to load the new/updated subagents.\n`);
    r.stdout(`    After restart, you can run: /riglane-run-workflow ${wfName}\n`);
  }

  return { created, updated, unchanged, deleted, total };
}

export async function initWorkflow(
  name: string,
  opts: InitWorkflowOptions = {},
): Promise<InitWorkflowResult> {
  return initWorkflowSync(name, opts);
}

export async function runInitWorkflowCli(
  argv: string[] = process.argv.slice(2),
  opts: InitWorkflowOptions = {},
): Promise<number> {
  const r = resolveOpts(opts);
  let parsed: { values: Record<string, string | boolean | undefined>; positionals: string[] };
  try {
    parsed = parseArgs({
      args: argv,
      options: { 'dry-run': { type: 'boolean' as const } },
      allowPositionals: true,
      strict: true,
    }) as { values: Record<string, string | boolean | undefined>; positionals: string[] };
  } catch (e) {
    r.stderr(`${e instanceof Error ? e.message : String(e)}\n`);
    return 2;
  }

  const name = parsed.positionals[0];
  if (!name) {
    r.stderr('usage: init-workflow <workflow-name> [--dry-run]\n');
    return 2;
  }
  if (parsed.positionals.length > 1) {
    r.stderr(`init-workflow: unrecognized arguments: ${parsed.positionals.slice(1).join(' ')}\n`);
    return 2;
  }

  const dryRun = Boolean(parsed.values['dry-run']);
  try {
    await initWorkflow(name, { ...opts, dryRun });
    return 0;
  } catch (e) {
    r.stderr(`ERROR: ${e instanceof Error ? e.message : String(e)}\n`);
    if (e instanceof WorkflowNotFoundError) return 1;
    if (e instanceof WorkflowMalformedError) return 2;
    if (e instanceof WorkflowFileWriteError) return 3;
    return 1;
  }
}
