
import { cpSync, mkdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { stringify as stringifyYaml } from 'yaml';

import { runDir } from './runs.js';

const SEGMENT_RE = /^[A-Za-z0-9._-]+$/;

function assertSafeSegment(segment: string, label: string): void {
  if (typeof segment !== 'string' || segment.length === 0) {
    throw new Error(`dynamic-runs: ${label} must be a non-empty string`);
  }
  if (segment === '.' || segment === '..') {
    throw new Error(`dynamic-runs: ${label} cannot be '.' or '..'`);
  }
  if (!SEGMENT_RE.test(segment)) {
    throw new Error(
      `dynamic-runs: ${label} contains unsafe characters: '${segment}'. ` +
        `Allowed: [A-Za-z0-9._-].`,
    );
  }
}

export function dynamicRootDir(agentDir: string, parentRunId: string): string {
  return join(runDir(agentDir, parentRunId), 'dynamic');
}

export function dynamicRuntimeDir(
  agentDir: string,
  parentRunId: string,
  stepName: string,
): string {
  assertSafeSegment(stepName, 'step_name');
  return join(dynamicRootDir(agentDir, parentRunId), stepName);
}

export function dynamicWorkflowPath(
  agentDir: string,
  parentRunId: string,
  stepName: string,
): string {
  return join(dynamicRuntimeDir(agentDir, parentRunId, stepName), 'workflow.yaml');
}

export function ensureDynamicRuntimeDir(
  agentDir: string,
  parentRunId: string,
  stepName: string,
): string {
  const dir = dynamicRuntimeDir(agentDir, parentRunId, stepName);
  mkdirSync(dir, { recursive: true });
  return dir;
}

export function dynamicRuntimeDirExists(
  agentDir: string,
  parentRunId: string,
  stepName: string,
): boolean {
  try {
    return statSync(dynamicRuntimeDir(agentDir, parentRunId, stepName)).isDirectory();
  } catch {
    return false;
  }
}

export function dynamicChildWorkflowName(
  parentWorkflow: string,
  parentRunId: string,
  stepName: string,
): string {
  const shortRun = parentRunId.replace(/[^A-Za-z0-9]/g, '').slice(0, 12) || 'run';
  return `dyn__${parentWorkflow}__${stepName}__${shortRun}`;
}

export interface DynamicOriginMeta {
  readonly parent_workflow: string;
  readonly parent_run_id: string;
  readonly parent_step: string;
  readonly parent_goal: string;
  readonly generated_at: string;
  readonly generated_by_orchestrator_model?: string;
}

export function composeDynamicWorkflowYaml(
  parsedDraft: Record<string, unknown>,
  childWorkflowName: string,
  origin: DynamicOriginMeta,
): string {
  const composed: Record<string, unknown> = {
    _dynamic_origin: { ...origin },
    name: childWorkflowName,
    version: 1,
    description:
      typeof parsedDraft.description === 'string' && parsedDraft.description.length > 0
        ? parsedDraft.description
        : `Generated by planning step '${origin.parent_step}' in workflow '${origin.parent_workflow}'`,
    steps: parsedDraft.steps,
  };
  return stringifyYaml(composed);
}

export function writeDynamicWorkflow(
  agentDir: string,
  parentWorkflow: string,
  parentRunId: string,
  stepName: string,
  parsedDraft: Record<string, unknown>,
  origin: DynamicOriginMeta,
): { path: string; childName: string } {
  const dir = ensureDynamicRuntimeDir(agentDir, parentRunId, stepName);
  const childName = dynamicChildWorkflowName(parentWorkflow, parentRunId, stepName);
  const yamlText = composeDynamicWorkflowYaml(parsedDraft, childName, origin);
  const path = join(dir, 'workflow.yaml');
  writeFileSync(path, yamlText, 'utf-8');
  return { path, childName };
}

export function copyStructsToDynamicRuntime(
  parentDefinitionDir: string,
  childWorkflowYamlPath: string,
): boolean {
  const src = join(parentDefinitionDir, 'structs');
  let isDir = false;
  try {
    isDir = statSync(src).isDirectory();
  } catch {
    isDir = false;
  }
  if (!isDir) return false;
  const dest = join(dirname(childWorkflowYamlPath), 'structs');
  cpSync(src, dest, { recursive: true, force: true });
  return true;
}
